DATA SEGMENT
  result DW 0
DATA ENDS
CODE SEGMENT
  ASSUME DS:DATA, CS:CODE
START:
  MOV AX, DATA
  MOV DS, AX
  MOV AX, 0038H
  MOV BX, 0010H
  SUB AX, BX
  MOV DS:[0016H], AX
  MOV AH, 4CH
  INT 21H
CODE ENDS
  END START
